export const arrow = <i className="fa-solid fa-arrow-right"></i>
export const cross = <i className="fa-regular fa-circle-xmark"></i>
export const cart = <i className="fa-solid fa-cart-shopping"></i>
export const breadcrumarrow = <i className="fa-solid fa-angle-right"></i>
export const drpdown = <i className="fa-solid fa-caret-down"></i>
export const insta = <i className="fa-brands fa-instagram"></i>
export const printrestry = <i className="fa-brands fa-pinterest"></i>
export const star = <i className="fa-solid fa-star"></i>
export const whatsapp = <i className="fa-brands fa-whatsapp"></i>
export const shopicon = <i className="fa-brands fa-shopify"></i>
export const starempty = <i className="fa-regular fa-star"></i>
export const starfull = <i className="fa-solid fa-star"></i>
export const rupees = <i className="fa-solid fa-indian-rupee-sign"></i>
export const world = <i className="fa-solid fa-earth-americas"></i>
export const offer = <i className="fa-solid fa-tag"></i>
export const secure = <i className="fa-solid fa-lock"></i>
export const facebook = <i className="fa-brands fa-facebook"></i>
export const twitter = <i className="fa-brands fa-twitter"></i>
export const youtube = <i className="fa-brands fa-youtube"></i>
export const leftarrow = <i className="fa-solid fa-arrow-left"></i>
export const remove = <i className="fa-solid fa-trash"></i>
export const search = <i className="fa-solid fa-magnifying-glass"></i>
export const squaredropdown = <i className="fa-solid fa-square-caret-down"></i>
export const email = <i className="fa-solid fa-envelope"></i>
export const phone = <i className="fa-solid fa-phone"></i>
export const like = <i className="fa-regular fa-heart"></i>
export const heart = <i className="fa-solid fa-heart"></i>